<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AlunosMap.php");

/**
 * AlunosDAO provides object-oriented access to the alunos table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AlunosDAO extends Phreezable
{
	/** @var int */
	public $IdAlu;

	/** @var int */
	public $IdTur;

	/** @var int */
	public $Webmail;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Endereco;

	/** @var string */
	public $Cidade;

	/** @var string */
	public $Bairro;

	/** @var string */
	public $Estado;

	/** @var string */
	public $Cep;

	/** @var string */
	public $Email;

	/** @var date */
	public $Nascimento;

	/** @var string */
	public $Cpf;

	/** @var string */
	public $Identidade;

	/** @var string */
	public $Orgao;

	/** @var int */
	public $EstadoCivil;

	/** @var int */
	public $Nacionalidade;

	/** @var string */
	public $Profissao;

	/** @var string */
	public $Telefone;

	/** @var string */
	public $Celular;

	/** @var string */
	public $Nextel;

	/** @var date */
	public $DataMatricula;

	/** @var time */
	public $HoraMatricula;

	/** @var int */
	public $Netbook;

	/** @var int */
	public $Idfun;

	/** @var int */
	public $IdIndica;

	/** @var int */
	public $MatrUnidade;



}
?>