<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AtendimentoMap.php");

/**
 * AtendimentoDAO provides object-oriented access to the atendimento table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AtendimentoDAO extends Phreezable
{
	/** @var int */
	public $IdAte;

	/** @var int */
	public $IdFun;

	/** @var int */
	public $Webmail;

	/** @var int */
	public $Unidade;

	/** @var char */
	public $Dia;

	/** @var char */
	public $Mes;

	/** @var char */
	public $Ano;

	/** @var int */
	public $Hora;

	/** @var int */
	public $Minuto;

	/** @var string */
	public $Nome;

	/** @var int */
	public $Soube;

	/** @var int */
	public $IdCur;

	/** @var string */
	public $Dias;

	/** @var string */
	public $Horario;

	/** @var string */
	public $Turno;

	/** @var string */
	public $Email;

	/** @var string */
	public $Tel1;

	/** @var string */
	public $Tel2;

	/** @var string */
	public $Tel3;

	/** @var string */
	public $Obs;



}
?>