<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CaPrematriculaMap.php");

/**
 * CaPrematriculaDAO provides object-oriented access to the ca_prematricula table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CaPrematriculaDAO extends Phreezable
{
	/** @var int */
	public $IdPre;

	/** @var int */
	public $IdTur;

	/** @var int */
	public $Webmail;

	/** @var int */
	public $Soube;

	/** @var date */
	public $Data;

	/** @var time */
	public $Hora;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Endereco;

	/** @var string */
	public $Cidade;

	/** @var string */
	public $Bairro;

	/** @var string */
	public $Estado;

	/** @var string */
	public $Cep;

	/** @var string */
	public $Email;

	/** @var string */
	public $Telefone;

	/** @var string */
	public $Celular;

	/** @var string */
	public $Nextel;

	/** @var int */
	public $Situacao;

	/** @var char */
	public $Turno;

	/** @var int */
	public $Curso;

	/** @var longtext */
	public $Resposta;

	/** @var int */
	public $Idfun;

	/** @var string */
	public $Ip;



}
?>