<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("DespesasMap.php");

/**
 * DespesasDAO provides object-oriented access to the despesas table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class DespesasDAO extends Phreezable
{
	/** @var int */
	public $IdDes;

	/** @var string */
	public $Conta;

	/** @var string */
	public $Descricao;

	/** @var float */
	public $Valor;

	/** @var date */
	public $Vencimento;

	/** @var float */
	public $Pago;

	/** @var date */
	public $Datapg;

	/** @var float */
	public $AulasWandall;



}
?>