<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("EmpresasMap.php");

/**
 * EmpresasDAO provides object-oriented access to the empresas table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class EmpresasDAO extends Phreezable
{
	/** @var int */
	public $IdEmp;

	/** @var string */
	public $Empresa;

	/** @var string */
	public $Cnpj;

	/** @var string */
	public $Endereco;

	/** @var string */
	public $Cidade;

	/** @var string */
	public $Bairro;

	/** @var string */
	public $Estado;

	/** @var string */
	public $Cep;

	/** @var string */
	public $Email;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Email1;

	/** @var string */
	public $Tel01;

	/** @var string */
	public $Contato02;

	/** @var string */
	public $Email2;

	/** @var string */
	public $Tel02;

	/** @var string */
	public $Contato03;

	/** @var string */
	public $Email3;

	/** @var string */
	public $Tel03;

	/** @var longtext */
	public $Obs;

	/** @var string */
	public $Nextel;

	/** @var string */
	public $Id;



}
?>