<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PagamentoMap.php");

/**
 * PagamentoDAO provides object-oriented access to the pagamento table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PagamentoDAO extends Phreezable
{
	/** @var int */
	public $IdPag;

	/** @var int */
	public $IdCli;

	/** @var int */
	public $IdPedido;

	/** @var string */
	public $Tipo;

	/** @var date */
	public $DataCri;

	/** @var time */
	public $HoraCri;

	/** @var string */
	public $Tid;

	/** @var float */
	public $ValorTotal;

	/** @var string */
	public $DataHoraRetorno;

	/** @var string */
	public $Bandeira;

	/** @var char */
	public $TipoVenda;

	/** @var char */
	public $Parcelas;

	/** @var char */
	public $Status;

	/** @var string */
	public $UrlAutenticacao;

	/** @var char */
	public $CodAutorizacao;

	/** @var char */
	public $Mensagem;

	/** @var char */
	public $DataHoraAutorizacao;

	/** @var char */
	public $Lr;

	/** @var char */
	public $Arp;



}
?>