<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("WdBannerhMap.php");

/**
 * WdBannerhDAO provides object-oriented access to the wd_bannerh table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class WdBannerhDAO extends Phreezable
{
	/** @var int */
	public $IdBan;

	/** @var string */
	public $Titulo;

	/** @var string */
	public $Imagem;

	/** @var string */
	public $Lin1;

	/** @var string */
	public $Lin2;

	/** @var string */
	public $Lin3;

	/** @var string */
	public $Lin4;

	/** @var string */
	public $Lin5;



}
?>