<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("WdCursosMap.php");

/**
 * WdCursosDAO provides object-oriented access to the wd_cursos table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class WdCursosDAO extends Phreezable
{
	/** @var string */
	public $Curso;

	/** @var int */
	public $IdCur;

	/** @var int */
	public $IdTip;

	/** @var int */
	public $Valido;

	/** @var int */
	public $Pesquisa;

	/** @var longtext */
	public $Objetivo;

	/** @var longtext */
	public $PreRequisito;

	/** @var longtext */
	public $Metodologia;

	/** @var int */
	public $Cargahora;

	/** @var string */
	public $Materia1;

	/** @var int */
	public $Idcur1;

	/** @var int */
	public $Cargah1;

	/** @var longtext */
	public $Conteudo1;

	/** @var string */
	public $Materia2;

	/** @var int */
	public $Idcur2;

	/** @var longtext */
	public $Conteudo2;

	/** @var int */
	public $Cargah2;

	/** @var string */
	public $Materia3;

	/** @var int */
	public $Idcur3;

	/** @var longtext */
	public $Conteudo3;

	/** @var int */
	public $Cargah3;

	/** @var string */
	public $Materia4;

	/** @var int */
	public $Idcur4;

	/** @var longtext */
	public $Conteudo4;

	/** @var int */
	public $Cargah4;

	/** @var string */
	public $Materia5;

	/** @var int */
	public $Idcur5;

	/** @var longtext */
	public $Conteudo5;

	/** @var int */
	public $Cargah5;

	/** @var string */
	public $Materia6;

	/** @var int */
	public $Idcur6;

	/** @var longtext */
	public $Conteudo6;

	/** @var int */
	public $Cargah6;

	/** @var string */
	public $Materia7;

	/** @var int */
	public $Idcur7;

	/** @var longtext */
	public $Conteudo7;

	/** @var int */
	public $Cargah7;

	/** @var string */
	public $Materia8;

	/** @var int */
	public $Idcur8;

	/** @var longtext */
	public $Conteudo8;

	/** @var int */
	public $Cargah8;

	/** @var string */
	public $Livro;

	/** @var string */
	public $Image;

	/** @var string */
	public $Banner;



}
?>