<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("WdProfessorMap.php");

/**
 * WdProfessorDAO provides object-oriented access to the wd_professor table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class WdProfessorDAO extends Phreezable
{
	/** @var int */
	public $IdPro;

	/** @var int */
	public $Ativo;

	/** @var string */
	public $Apelido;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Tel;

	/** @var string */
	public $Cel;

	/** @var string */
	public $Email;

	/** @var string */
	public $Senha;

	/** @var longtext */
	public $Descricao;

	/** @var string */
	public $Certificado1;

	/** @var string */
	public $Certificado2;

	/** @var string */
	public $Certificado3;

	/** @var string */
	public $Certificado4;

	/** @var string */
	public $Certificado5;



}
?>