<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("WdTurmasMap.php");

/**
 * WdTurmasDAO provides object-oriented access to the wd_turmas table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class WdTurmasDAO extends Phreezable
{
	/** @var int */
	public $IdTur;

	/** @var int */
	public $IdUni;

	/** @var int */
	public $Due;

	/** @var int */
	public $Aberta;

	/** @var int */
	public $Andamento;

	/** @var int */
	public $IdCur;

	/** @var int */
	public $IdPro;

	/** @var date */
	public $Inicio;

	/** @var date */
	public $Termino;

	/** @var int */
	public $Aulas;

	/** @var string */
	public $Turno;

	/** @var string */
	public $Dias;

	/** @var string */
	public $Horario;

	/** @var int */
	public $Vagas;

	/** @var int */
	public $Pre;

	/** @var int */
	public $Matriculas;

	/** @var int */
	public $Sala;

	/** @var string */
	public $Status;



}
?>