<?php
/** @package WandallCa::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("WdValorcursosMap.php");

/**
 * WdValorcursosDAO provides object-oriented access to the wd_valorcursos table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package WandallCa::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class WdValorcursosDAO extends Phreezable
{
	/** @var int */
	public $IdVar;

	/** @var int */
	public $IdCur;

	/** @var float */
	public $Valor;

	/** @var float */
	public $Desconto;

	/** @var string */
	public $Material;

	/** @var string */
	public $Desc0;

	/** @var string */
	public $Desc1;

	/** @var string */
	public $Desc2;

	/** @var string */
	public $Desc3;

	/** @var float */
	public $Avista1;

	/** @var float */
	public $Desc11;

	/** @var float */
	public $Desc12;

	/** @var float */
	public $Desc13;

	/** @var float */
	public $Desc14;

	/** @var float */
	public $Desc15;

	/** @var float */
	public $Desc16;

	/** @var float */
	public $Avista2;

	/** @var float */
	public $Desc21;

	/** @var float */
	public $Desc22;

	/** @var float */
	public $Desc23;

	/** @var float */
	public $Desc24;

	/** @var float */
	public $Desc25;

	/** @var float */
	public $Desc26;



}
?>